version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NGINX}
    restart: unless-stopped
    tty: true
    ports:
      - ${NGINX_80_PORT}:80
      - ${NGINX_443_PORT}:443
    volumes:
      - ${PATH_SALESUP}:/var/www/salesup
      - ./containers/php/html:/var/www/default
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      default:
        ipv4_address: ${NGINX_INTERNAL_IP}
    depends_on:
      - php
