version: '3'
services:

  mysql:
    image: ${MYSQL_IMAGE}
    platform: ${MYSQL_IMAGE_PLATFORM}
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    container_name: ${CONTAINER_DB}
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./containers/db/db_struucture.sql:/docker-entrypoint-initdb.d/mysql.sql
      - ./containers/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./containers/db/mysql/data:/var/lib/mysql
      - ${PATH_SALESUP}:/var/www/salesup
      - db-exec:/usr/bin
      - ./containers/db/files_bridge:/tmp/files_bridge

  #Phpmyadmin Service
  phpmyadmin:
    container_name: ${CONTAINER_PHPMYADMIN}
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOSTS: ${PMA_HOSTS}
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 250M
    volumes:
      - ./containers/phpmyadmin/upload.ini:/usr/local/etc/php/php.ini
volumes:
  db-exec:
